web:
  volumes:
   - "~/SITES/docker:/data"
  links:
    - "db:mysql"
  extends:
    file: docker-compose.common.yml
    service: web
db:
  extends:
    file: docker-compose.common.yml
    service: db
  ports:
    - "3306:3306"
  volumes_from:
    - db_data
db_data:
  extends:
    file: docker-compose.common.yml
    service: db_data
