hg_web:
  image: htmlgraphic/apache:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "hg_db:mysql"
  environment:
    - NODE_ENVIRONMENT=production
    - LOG_TOKEN=$LOG_TOKEN
hg_db:
  image: tutum/mysql:5.5
  volumes_from:
    - hg_db_data
  expose:
    - "3306"
  environment:
    - ON_CREATE_DB=htmlgraphic
    - MYSQL_PASS="mysql123"
hg_db_data:
    image: busybox
    volumes:
      - "/var/lib/mysql"
