version: "3"
services:
  web:
    image: 'htmlgraphic/apache:envoyer'
    volumes:
      - "/Volumes/Case/SITES/docker:/data" # <- Change to preferred local working dir
     #- "/c/Users/southpark/docker:/data"
    links:
      - "db:mysql"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENVIRONMENT=dev
    env_file:
      - .env
  db:
    image: 'htmlgraphic/mysql:5.7.18'
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=new_passwordac
      - MYSQL_DATABASE=htmlgraphic
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=new_password
volumes:
  db-data:
