hg-web:
  image: htmlgraphic/apache:latest
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NODE_ENVIRONMENT=production
  env_file:
    - .env
  links:
    - "hg-db:mysql"
hg-db:
  image: htmlgraphic/mysql:5.5
  environment:
    - ON_CREATE_DB=htmlgraphic
    - MYSQL_PASS=new_password
  expose:
    - "3306"
db-data:
  image: busybox:latest
  volumes:
    - "/var/lib/mysql"
