hg-web:
  image: htmlgraphic/apache:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "hg-db:mysql"
  environment:
    - NODE_ENVIRONMENT=production \
    - SASL_USER=p08tf1X \
    - SASL_PASS=p@ssw0Rd \
hg-db:
  image: htmlgraphic/mysql:5.5
  volumes_from:
    - hg-db-data
  expose:
    - "3306"
  environment:
    - ON_CREATE_DB=htmlgraphic
hg-db-data:
    image: busybox
    volumes:
      - "/var/lib/mysql"
