hg-web:
  extends:
    file: docker-compose.common.yml
    service: web
  env_file:
    - .env
  environment:
    - NODE_ENVIRONMENT=production
  links:
    - "hg-db:mysql"
hg-db:
  extends:
    file: docker-compose.common.yml
    service: db
  expose:
    - "3306"
db-data:
  extends:
    file: docker-compose.common.yml
    service: db-data
