web:
  volumes:
   - "~/SITES/docker:/data"
   #- "/c/Users/southpark/docker:/data"
  links:
    - "db:mysql"
  extends:
    file: docker-compose.common.yml
    service: web
  environment:
    - NODE_ENVIRONMENT=dev
db:
  extends:
    file: docker-compose.common.yml
    service: db
  volumes_from:
    - db-data
  ports:
    - "3306:3306"
db-data:
  extends:
    file: docker-compose.common.yml
    service: db-data
