apache:
  image: htmlgraphic/apache:latest
  container_name: apache
  ports:
    - "80:80"
    - "443:433"
db:
  image: tutum/mysql:5.5
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - ON_CREATE_DB=htmlgraphic
    - MYSQL_PASS=mysql123
db_data:
    image: busybox
    volumes:
      - "/var/lib/mysql"
