web:
  image: htmlgraphic/apache:envoyer
  ports:
    - "80:80"
    - "443:443"
  env_file:
    - .env
db:
  image: htmlgraphic/mysql:5.5
  environment:
    - ON_CREATE_DB=htmlgraphic
    - MYSQL_PASS=new_password
db-data:
  image: busybox:latest
  volumes:
    - "/var/lib/mysql"
